### ISSUE TITLE
Make link to here from JUMP 

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/monorepo#37] opened 2024-05-07 20:37 UTC
broad.io/jump-explore goes to [here](https://github.com/broadinstitute/monorepo/tree/main/libs/jump_rr) which is great, but then there is also this:
https://broadinstitute.github.io/2023_12_JUMP_data_only_vignettes/howto/tutorial_basic.html

Those two pages ought to link to each other so people can find the resources. Even better if the content is combined and just in one location?

**Comment by afermg** [comment] 2024-05-07 22:06
I will add bidirectional links, but we should keep both repositories separate because one is JUMP-stories, tutorials and resources while this monorepo is all about tools and how to reproduce the high-content analysis. I think broad.io/jump-explore should be equal to broad.io/jump and point towards the user-facing documentation.

**Comment by afermg** [comment] 2024-05-07 23:10
After navigating on the JUMP Central website again, I think we are indeed missing a front-and-centre approach to the important links. I added them in both cases:
- On JUMP Central
![image](https://github.com/broadinstitute/monorepo/assets/14353896/8b7574ea-53c8-4a78-8323-275d8d6e7208)

- On the monorepo (all our important shared tools)
![image](https://github.com/broadinstitute/monorepo/assets/14353896/acb410de-5c05-4712-90a0-a584830ffc27)

Let me know if this suffices to close the issue. Thanks a lot for the feeback! :)

**Closed** 2024-05-08 14:33 UTC
